const input = document.querySelector('.search__input');
const searchList = document.querySelector('.search__showList');

const hotelData = [
  'Marks,ErnserandMante',
  'HansenandSons',
  'Brakus,WymanandCrooks',
  'Yundt,WuckertandConn',
  'Bins,HeathcoteandHerzog',
  'Nolan,HarberandGleason',
  'Lang-Jenkins',
  'Bogan-Gerlach',
  'AndersonGroup',
  'Wolf,StammandSchowalter',
  'Thiel-Hegmann',
  'Bednar-Bauch',
  'CorkeryandSons',
  'HyattLLC',
  'Cole,JohnsonandMcDermott',
  'Gleichner,TurcotteandSchroeder',
  'Turcotte-Jacobi',
  'Blanda-Ernser',
  'LefflerGroup',
  'Mayert-Volkman',
  'MannGroup',
  'Kuhic-Ratke',
  'Klocko-Kohler',
  'StrackeGroup',
  'Anderson,SchmittandKunze',
  'McLaughlin-Carter',
  'Mertz-Bahringer',
  'JacobiandSons',
  'MohrLLC',
  'Mraz-Rodriguez',
  'Anderson-Greenholt',
  'Gulgowski,HaleyandHowell',
  'Mertz,BeahanandBoyle',
  'Boehm,BednarandBahringer',
  'Runolfsdottir,KuvalisandWunsch',
  'ToyLLC',
  'Tremblay,HoppeandPowlowski',
  'Greenfelder,JastandWilkinson',
  'HalvorsonGroup',
  'Pouros-Bailey',
  'Funk-Kub',
  'Powlowski-Block',
  'LeuschkeandSons',
  'Price-Ryan',
  'Goyette-Bartoletti',
  'Romaguera,MannandLeannon',
  'Rempel-Fay',
  'Franecki,RutherfordandSatterfield',
  'Donnelly,SkilesandWilliamson',
  'KihnLLC',
  'Schmeler,CollinsandHettinger',
  'Lindgren-Buckridge',
  'Batz-Predovic',
  'Koch,SchmelerandMertz',
  'Cartwright,DavisandFerry',
  'ConnellyandSons',
  'Hansen,LakinandWyman',
  'Hauck,LebsackandKlein',
  'Hyatt-VonRueden',
  'Schiller-Lowe',
  'Robel,WhiteandGoodwin',
  'Hickle,JacobsonandTorp',
  'Stracke,FeeneyandMonahan',
  'RohanLLC',
  'Predovic,AltenwerthandTerry',
  "Gutkowski-D'Amore",
  'Gusikowski,KohlerandWaelchi',
  'HilpertGroup',
  'Maggio-Hettinger',
  'KoelpinGroup',
  "Predovic,D'AmoreandDoyle",
  'Quitzon-Kunze',
  'King,FramiandKlein',
  'Koepp,RennerandMueller',
  'Walter,GorczanyandBins',
  'Barton,KertzmannandRolfson',
  'LednerGroup',
  'Bernhard-Turcotte',
  'Medhurst-Altenwerth',
  'Rippin-Trantow',
  'Marquardt,OrnandCollier',
  'Quigley-Beahan',
  'KreigerGroup',
  'Gutkowski-Lubowitz',
  'TorpInc',
  'MurrayInc',
  'Lebsack,ReichelandRomaguera',
  'Legros,HansenandDuBuque',
  'KautzerGroup',
  'LefflerInc',
  'DavisandSons',
  'Abbott,HansenandBogan',
  'Heidenreich-Hermiston',
  'Pagac-Tillman',
  "O'KonGroup",
  'Heaney-Smith',
  'Bogan,WestandGrady',
  'Bogisich-Johnston',
  'TorpLLC',
  'Spinka-Robel',
  'Treutel,EmardandBashirian',
  'Bailey-Feil',
  'Herzog-Green',
  'Ferry,WeissnatandZboncak',
  'Rowe,KemmerandWunsch',
  'BodeInc',
  'Stehr-Adams',
  'Stracke,AnkundingandWilderman',
  'StiedemannLLC',
  'Feeney-Grady',
  'Ratke,MedhurstandHintz',
  'Schneider,TorpandQuigley',
  'Keeling,MacejkovicandGibson',
  'Veum-Lockman',
  'Pouros,RempelandHackett',
  'ChamplinandSons',
  'Fay-Greenfelder',
  'Koepp,BalistreriandBreitenberg',
  'Littel-Prohaska',
  'Botsford,VandervortandBotsford',
  'Lind-Kirlin',
  'LednerandSons',
  'Bauch-Bosco',
  'Morissette,SchuppeandEbert',
  'Konopelski,LittleandKertzmann',
  'Aufderhar,GreenfelderandVonRueden',
  'ChristiansenGroup',
  'ZulaufInc',
  'Mohr,JakubowskiandBayer',
  'TowneandSons',
  'Will-Greenfelder',
  'Quigley-McGlynn',
  'Predovic,DickiandCremin',
  "Kuvalis-O'Hara",
  'ReynoldsLLC',
  'EmardInc',
  "O'HaraandSons",
  'Sipes,SkilesandJacobi',
  'Schultz,MorissetteandHammes',
  'Glover-King',
  'HeathcoteandSons',
  'Legros-Greenholt',
  "O'Kon-Veum",
  'Hyatt,SchneiderandUpton',
  'Feeney-Watsica',
  'McKenzie,PfefferandHuel',
  'Wiza-Daniel',
  'Schaefer,BeckerandGoodwin',
  'Durgan,BeahanandKrajcik',
];

function getResult(e) {
  const inputValue = e.target.value;
  searchList.innerHTML = '';
  const foundHotels = hotelData.filter(hotel => {
    return hotel.toUpperCase().startsWith(inputValue.toUpperCase());
  });

  if (foundHotels.length === hotelData.length) {
    searchList.style.display = 'none';
  } else {
    searchList.style.display = 'block';
  }

  foundHotels.forEach(foundhotel => {
    creatNode(foundhotel);
  });
}

function creatNode(foundHotel) {
  const listItem = document.createElement('li');
  listItem.classList.add('search__list-item');
  listItem.innerText = foundHotel;
  searchList.append(listItem);
}

input.addEventListener('keyup', getResult);
